version: '3.3'
services:

  keycloak:
    image: "jboss/keycloak:6.0.1"
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - PROXY_ADDRESS_FORWARDING=true
    networks:
      - backend
    volumes:
        - "./standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml"

  nginx:
    image: "nginx"
    ports:
      - 8443:8443
    depends_on:
      - "keycloak"
    volumes:
      - "./localhost.pem:/etc/nginx/certs/localhost.pem"
      - "./localhost_sec_key_wo_pass.pem:/etc/nginx/certs/localhost_sec_key_wo_pass.pem"
      - "./localhost.conf:/etc/nginx/conf.d/localhost.conf"
    networks:
      - backend
      - web

networks:
  web:
    driver: bridge
  backend:
    driver: bridge
